config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :assets
  # devise_for :users
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resources :comments, only: [:create, :update, :destroy, :index]
  resources :projects do
    resources :cards do
      collection do
      end
    end
  end
  get '/:token' => 'projects#public_share', :constraints => { subdomain: /share/ }, as: :project_public_share
  get '/:token/card' => 'cards#public_share', :constraints => { subdomain: /share/ }, as: :card_public_share
  get 'projects/tags/:tag', to: 'projects#index', as: :tag
  get 'projects/:project_id/cards/tags/:tag', to: 'projects#show', as: :card_tag
  # match '/:projects(/:public_share_token)', to: 'projects#show', via: [:get]
  root to: 'projects#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
	include AlgoliaSearch
	extend FriendlyId
	acts_as_taggable_on :tags, :cards

  belongs_to :user
	has_many :cards,  dependent: :destroy
  has_many :comments, as: :commentable, dependent: :delete_all
  has_many :card_comments, source: :comments, through: :cards

	before_validation :set_unique_public_share_token, on: :create

	algoliasearch index_name: "Project" do
    attributes :title, :description, :tag_list
    searchableAttributes ['title']
  end

  friendly_id :public_share_token, use: :slugged

  def public_share_url
    subdomain, host = case Rails.env
                      when 'development' then ['share',         'timblee.dev']
                      when 'staging'     then ['share-staging', 'timblee.io']
                      when 'prep'        then ['share-prep',    'timblee.io']
                      when 'production'  then ['share',         'timblee.io']
                      end

    options = { subdomain: subdomain, host: host }

    options.merge!(port: '3000')      if Rails.env.development?
    options.merge!(protocol: 'https') if Rails.env.production?
    Rails.application.routes.url_helpers.project_public_share_url(public_share_token, options)
  end

  def set_unique_public_share_token
    self.public_share_token = Digest::SHA1.hexdigest([Time.now, rand].join)[0,10]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:home]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :fetch_project_from_token, only: [:public_share]

  # GET /projects
  # GET /projects.json
  def index
    if(params[:tag])
      @projects = current_user.projects.tagged_with(params[:tag])
    else
      @projects = current_user.projects
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    if(params[:tag])
      @cards = @project.cards.tagged_with(params[:tag])
    else
      @cards = @project.cards
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  def home
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def public_share
    @cards = @project.cards
    render :show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.friendly.find(params[:id] || params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :tag_list)
    end

    def fetch_project_from_token
      unless @project = current_user.projects.find_by(public_share_token: params[:token])
        redirect_to root_path, alert: 'The share token is invalid.' and return
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :project_title %>
  </div>

  <div class="field">
    <%= form.label :description%>
    <%= form.text_field :description, id: :project_description %>
  </div>

  <div class="field">
    <%= form.label :tag_list, "Tags (Seperated by commas)" %>
    <%= form.text_field :tag_list, id: :project_tag_list, value: project.tag_list.join(',') %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/home.html.erb
This is the Home page of website

app/views/projects/index.html.erb
  <p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-2">
    <h3>Tags ( <%= current_user.projects.tag_counts.count %>)</h3>
    <ul class="list-group">
      <% tag_cloud current_user.projects.tag_counts, %w[s m l] do |tag, css_class| %>
        <li class="list-group-item"><%= link_to tag.name, tag_path(tag.name), class: css_class %> </li>
      <% end %>
    </ul>
  </div>
  <div class="col-sm-10">
    <h1>Projects</h1>
    <div class="row">
      <div class="aa-input-container" id="aa-input-container">
          <input type="search" id="aa-search-input" class="aa-input-search" placeholder="Search for players or teams..." name="search" autocomplete="off" />
          <svg class="aa-input-icon" viewBox="654 -372 1664 1664">
              <path d="M1806,332c0-123.3-43.8-228.8-131.5-316.5C1586.8-72.2,1481.3-116,1358-116s-228.8,43.8-316.5,131.5  C953.8,103.2,910,208.7,910,332s43.8,228.8,131.5,316.5C1129.2,736.2,1234.7,780,1358,780s228.8-43.8,316.5-131.5  C1762.2,560.8,1806,455.3,1806,332z M2318,1164c0,34.7-12.7,64.7-38,90s-55.3,38-90,38c-36,0-66-12.7-90-38l-343-342  c-119.3,82.7-252.3,124-399,124c-95.3,0-186.5-18.5-273.5-55.5s-162-87-225-150s-113-138-150-225S654,427.3,654,332  s18.5-186.5,55.5-273.5s87-162,150-225s138-113,225-150S1262.7-372,1358-372s186.5,18.5,273.5,55.5s162,87,225,150s113,138,150,225  S2062,236.7,2062,332c0,146.7-41.3,279.7-124,399l343,343C2305.7,1098.7,2318,1128.7,2318,1164z" />
          </svg>
      </div>
      <%= link_to 'New Project', new_project_path, class: "btn btn-outline-success" %>
    </div>

    </br>

    <div class="row" id='project-list'>
      <% @projects.each do |project| %>
      <div class="col-sm-3">
        <div class="card" style="width: 20rem;">
          <img class="card-img-top" src="..." alt="Card image cap">
          <div class="card-block">
            <h4 class="card-title"><%= project.title %></h4>
            <p><%= project.description %></p>
            <p><a href="#" role="button"><%= link_to 'Show', project_path(project), class: "btn btn-primary" %></a>
            <a href="#" role="button"><%= link_to 'Edit', edit_project_path(project), class: "btn btn-default" %></a>
            <a href="#" role="button"><%= link_to 'Destroy', project_path(project), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></a>
            </p>
            <p> Tags: <%= raw project.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %> </p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
    <script type="text/javascript">
      var client = algoliasearch("FX5ZZE6G1R", "bcac623b0ae454a42a03938910937fda");
      var index = client.initIndex('Project');
      //initialize autocomplete on search input (ID selector must match)
       $('#aa-search-input').autocomplete(
        {hint: false}, [
        {
          source: $.fn.autocomplete.sources.hits(index, { hitsPerPage: 5 }),
          //value to be displayed in input control after user's suggestion selection
          displayKey: 'title',
          //hash of templates used when rendering dataset
          templates: {
            //'suggestion' templating function used to render a single suggestion
            suggestion: function(suggestion) {
              console.log("<a href=/projects/"+suggestion.objectID +'>' + suggestion._highlightResult.title.value + '</a>');
              return "<a href=/projects/"+ suggestion.objectID +'>' + suggestion._highlightResult.title.value + '</a>';
            }
          }
        }
      ]).on('autocomplete:selected', function(event, suggestion) {
          $('#project-list').html(
            '<div class="col-sm-3"><div class="card" style="width: 20rem;"><p> Project ID : '+ suggestion.objectID +
            '</p><div class="card-block">'+
                  '<h4 class="card-title">'+ suggestion.title +'</h4>'+
                  '<p>'+suggestion.description+'</p>'+
                  '<p>'+ '<a href=/projects/'+ suggestion.objectID +'  role="button"> show</a></p></div></div></div>');
        })
    </script>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-sm-2">
  <!-- This Needs to be repaced by Project.cards.cloud tags -->
    <h3>Tags ( <%= @project.cards.tag_counts.count %>)</h3>
    <ul class="list-group">
      <% tag_cloud @project.cards.tag_counts, %w[s m l] do |tag, css_class| %>
        <li class="list-group-item"><%= link_to tag.name, card_tag_path(@project, tag.name), class: css_class %> </li>
      <% end %>
    </ul>
  </div>
  <div class="col-sm-10">
    <p id="notice"><%= notice %></p>
    <h4><%= @project.title.titleize %></h4>
    <h3><%= @project.cards.count %> Cards</h3>
    <div class="row">
      <div class="aa-input-container" id="aa-input-container">
          <input type="search" id="aa-search-input" class="aa-input-search" placeholder="Search for players or teams..." name="search" autocomplete="off" />
          <svg class="aa-input-icon" viewBox="654 -372 1664 1664">
              <path d="M1806,332c0-123.3-43.8-228.8-131.5-316.5C1586.8-72.2,1481.3-116,1358-116s-228.8,43.8-316.5,131.5  C953.8,103.2,910,208.7,910,332s43.8,228.8,131.5,316.5C1129.2,736.2,1234.7,780,1358,780s228.8-43.8,316.5-131.5  C1762.2,560.routes8,1806,455.3,1806,332z M2318,1164c0,34.7-12.7,64.7-38,90s-55.3,38-90,38c-36,0-66-12.7-90-38l-343-342  c-119.3,82.7-252.3,124-399,124c-95.3,0-186.5-18.5-273.5-55.5s-162-87-225-150s-113-138-150-225S654,427.3,654,332  s18.5-186.5,55.5-273.5s87-162,150-225s138-113,225-150S1262.7-372,1358-372s186.5,18.5,273.5,55.5s162,87,225,150s113,138,150,225  S2062,236.7,2062,332c0,146.7-41.3,279.7-124,399l343,343C2305.7,1098.7,2318,1128.7,2318,1164z" />
          </svg>
      </div>
      <%= link_to 'New Card', new_project_card_path(@project.id), class: "btn btn-outline-success" %>
      <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#projectCommentsModal">Comments</button>
    </div>

    </br>

    <div class="row" id='card-list'>
      <% @cards.each do |card| %>
      <div class="col-sm-3">
        <div class="card" style="width: 20rem;">
          <img class="card-img-top" src="..." alt="Card image cap">
          <div class="card-block">
            <h4 class="card-title"><%= card.title %></h4>
            <p><%= card.description %></p>
            <p><a href="#" role="button"><%= link_to 'Show', project_card_path(@project, card), class: "btn btn-default" %></a>
            <a href="#" role="button"><%= link_to 'Edit', edit_project_card_path(@project, card), class: "btn btn-default" %></a>
            <%= link_to 'Destroy', [@project, card], confirm: 'Are you sure?', class: "btn btn-default", method: :delete %>
            </p>
            <p> Tags: <%= raw card.tag_list.map { |t| link_to t, card_tag_path(@project, t) }.join(', ') %> </p>
          </div>
        </div>
      </div>
      <% end %>
    </div>

    <script type="text/javascript">
      var client = algoliasearch("FX5ZZE6G1R", "bcac623b0ae454a42a03938910937fda");
      var index = client.initIndex('Card');
      //initialize autocomplete on search input (ID selector must match)
       $('#aa-search-input').autocomplete(
        {hint: false}, [
        {
          source: $.fn.autocomplete.sources.hits(index, { hitsPerPage: 5 }),
          //value to be displayed in input control after user's suggestion selection
          displayKey: 'title',
          //hash of templates used when rendering dataset
          templates: {
            //'suggestion' templating function used to render a single suggestion
            suggestion: function(suggestion) {
              console.log("<a href=/projects/"+suggestion.objectID +'>' + suggestion._highlightResult.title.value + '</a>');
              return "<a href=/projects/"+ suggestion.objectID +'>' + suggestion._highlightResult.title.value + '</a>';
            }
          }
        }
      ]).on('autocomplete:selected', function(event, suggestion) {
          $('#card-list').html(
            '<div class="col-sm-3"><div class="card" style="width: 20rem;"><p> Project ID : '+ suggestion.objectID +
            '</p><div class="card-block">'+
                  '<h4 class="card-title">'+ suggestion.title +'</h4>'+
                  '<p>'+suggestion.description+'</p>'+
                  '<p>'+ '<a href=/projects/'+ suggestion.objectID +'  role="button"> show</a></p></div></div></div>');
        })
    </script>
  </div>
</div>

<%= render "shared/project_comments", locals: { project: @project }%>