config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :assets
  # devise_for :users
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resources :comments, only: [:create, :update, :destroy, :index]
  resources :projects do
    resources :cards do
      collection do
      end
    end
  end
  get '/:token' => 'projects#public_share', :constraints => { subdomain: /share/ }, as: :project_public_share
  get '/:token/card' => 'cards#public_share', :constraints => { subdomain: /share/ }, as: :card_public_share
  get 'projects/tags/:tag', to: 'projects#index', as: :tag
  get 'projects/:project_id/cards/tags/:tag', to: 'projects#show', as: :card_tag
  # match '/:projects(/:public_share_token)', to: 'projects#show', via: [:get]
  root to: 'projects#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
  include AlgoliaSearch
  extend FriendlyId

  after_create :increment_cards_count_of_current_user
  after_destroy :decrement_cards_count_of_current_user

  belongs_to :project
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :assets, dependent: :destroy

  acts_as_taggable_on :tags
  before_validation :set_unique_public_share_token, on: :create


  algoliasearch index_name: "Card" do
    attributes :title, :description, :tag_list
    searchableAttributes ['title']
  end

  friendly_id :public_share_token, use: :slugged

  def public_share_url
    subdomain, host = case Rails.env
                      when 'development' then ['share',         'timblee.dev']
                      when 'staging'     then ['share-staging', 'timblee.io']
                      when 'prep'        then ['share-prep',    'timblee.io']
                      when 'production'  then ['share',         'timblee.io']
                      end

    options = { subdomain: subdomain, host: host }

    options.merge!(port: '3000')      if Rails.env.development?
    options.merge!(protocol: 'https') if Rails.env.production?
    Rails.application.routes.url_helpers.card_public_share_url(public_share_token, options)
  end

  def set_unique_public_share_token
    self.public_share_token = Digest::SHA1.hexdigest([Time.now, rand].join)[0,10]
  end

  private
    def increment_cards_count_of_current_user
      User.current_user.increment!(:cards_created)
    end

    def decrement_cards_count_of_current_user
      User.current_user.decrement!(:cards_created)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :new, :create, :index]
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = @project.cards
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = @project.cards.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = @project.cards.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to project_path(@project), notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to project_path(@project), notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to project_path(@project), notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = @project.cards.friendly.find(params[:id])
    end

    def set_project
      @project = Project.friendly.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:title, :description, :project_id, :tag_list)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for([@project, @card], local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :card_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :card_description %>
  </div>

  <div class="field">
    <%= form.label :tag_list %>
    <%= form.text_field :tag_list, id: :card_description, value: card.tag_list.join(',') %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', project_card_path([@project, @card]) %> |
<%= link_to 'Back', project_path(@project) %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.title %></td>
        <td><%= card.description %></td>
        <td><%= card.project %></td>
        <td><%= link_to 'Show', project_card_path(@project, card) %></td>
        <td><%= link_to 'Edit', edit_project_card_path(@project, card) %></td>
        <td><%= link_to 'Destroy', project_card_path(@project, card), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_project_card_path(@project) %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

app/views/cards/show.html.erb
<div class="row">
  <div class="col-md-3">
    <strong>Title:</strong>
    <%= @card.title %> </br>
    <strong>Description:</strong>
    <%= @card.description %>
    <hr>
      <p> Tags: <%= raw @card.tag_list.map { |t| link_to t, card_tag_path(@project, t) }.join(', ') %> </p>
      <input type="text" id="docs" value="<%= @card.tag_list %>" data-role="tagsinput" />
    <hr>
    <div id="card_assets"> Documents here
      <input type="text" id="docs" value="Amsterdam,Washington,Sydney,Beijing,Cairo" data-role="tagsinput" />
      <input type="button" value="Upload" onclick="showPicker()" />
    </div>
    <hr>
      <div class="input-group">
        <span class="input-group-addon" id="basic-addon1">&#128279;</span>
        <input type="text" class="form-control" id="external-site-url", placeholder="Please enter external site url here ...">
      </div>
    <hr>
    <%= render partial: "shared/card_comments", locals: { card: @card } %>
  </div>
  <div class="col-md-9">
    This is iframe loader
    <div id='iframe-container'>
      <iframe id="website-loader" style="width: 100%;min-height: 600px;" src="https://timblee.com/"></iframe>
    </div>
  </div>
</div>


<!-- [{"filename":"2017-03-10-22-20-36-457.jpg.png","handle":"pRzRPDkR5qRqDYdC63sL","mimetype":"image/png","originalPath":"2017-03-10-22-20-36-457.jpg","size":298819,"source":"local_file_system","url":"https://cdn.filestackcontent.com/pRzRPDkR5qRqDYdC63sL","originalFile":{"name":"2017-03-10-22-20-36-457.jpg","type":"image/jpeg","size":79616},"status":"Stored"}] -->
<!-- File stack upload logic  -->
<script>

  var client = filestack.init('A6vmsOMQtTAW8anaFhDhWz');
  var card_id = <%= @card.id %>;
  function showPicker() {
    client.pick({
    }).then(function(result) {
      console.log(JSON.stringify(result));
      // $('#user_avatar_url').val(result.filesUploaded[0].url);
      var uploaded_file = result.filesUploaded[0];
      console.log(uploaded_file);
      // createNewAssetForCard(uploaded_file);
    });
  }

  function createNewAssetForCard(uploaded_file){
    alert("G");
    $.ajax({
      url: 'http://localhost:3000/assets',
      method: 'post',
      dataType: 'script',
      data: { file_name: uploaded_file.filename, file_type: uploaded_file.mimetype, file_source: uploaded_file.source, file_link: uploaded_file.url, card_id: card_id },
      success: function(result) {
        console.log(result);
      },
      error: function(result) {
        console.log(result.responseText)
      }
    });
  }

  var external_site_url = "https://timblee.com/";
  $( "#external-site-url" ).change(function() {
    external_site_url = $(this).val();
    $("#iframe-container").empty();
    $("#iframe-container").append("<iframe style='width: 100%;min-height: 600px;' src='" + external_site_url + "' />");
  });

</script>

<!-- File stack upload logic  end here -->

<%#= link_to 'Edit', edit_project_card_path(@project, @card) %>
<%#= link_to 'Back', project_cards_path(@project) %>